#!/bin/sh -x
for f in libXau libxcb libpixman libpciaccess libfontenc libXdmcp libdrm xtrans freetype fontconfig libICE libSM libX11 libXext libXfixes libXt libXv libxkbfile libXi libXfont libXinerama libXmu libXtst libXrender libXrandr libXft
do cd "$f"; ./"$f".sld; echo ""$f" built"; sleep 2; cd ../; done
